name: "Main workflow"
on: push

jobs:
  configure:
    runs-on: ubuntu-latest
    outputs:
      uid_gid: ${{ steps.get-user.outputs.uid_gid }}
    steps:
      - id: get-user
        run: echo "::set-output name=uid_gid::$(id -u):$(id -g)"

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install deps
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10
          brew install conan
          conan config install https://github.com/conan-io/conanclientcert.git
      - run: cmake -DCMAKE_BUILD_TYPE=Debug . && make

  check_version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get-version.outputs.version }}
      exists: ${{ steps.get-version.outputs.exists }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          submodules: true
      - id: get-version
        name: Get zxlib version
        run: echo ::set-output name=version::$(./scripts/get_version.sh)
      - id: tag-exists
        name: Check if version exists
        run: |
          if git rev-parse ${{ steps.get-version.outputs.version }} >/dev/null 2>&1; then
            echo ::set-output name=exists::true
          else
            echo ::set-output name=exists::false
          fi
      - name: Fail if tag exists
        if: ${{ steps.tag-exists.outputs.exists == 'true' }}
        run: exit 1

  tag:
    runs-on: ubuntu-latest
    needs:
      - build
      - check_version
    if: ${{ needs.check_version.outputs.exists != 'true' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.check_version.outputs.version }}
